#!/usr/bin/env ruby

# tries to update the untranslated strings with
# automatic google translations to help manual translators
# Courtesy limit: 100,000 characters/day

RAILS_HOME = File.expand_path(File.join(File.dirname(__FILE__)+"/../.."))
ENV['RAILS_ENV'] = case ARGV.first
  when "p"; "production"
  when "d"; "development"
  when "t"; "test"
  else
    ARGV.first || ENV['RAILS_ENV'] || 'development'
end

require RAILS_HOME + '/config/boot.rb'
require RAILS_HOME + '/config/environment'
require RAILS_HOME + '/libhelp/translation'

Translation::GoogleTranslate.run
