#!/usr/bin/env ruby

# Initializes the TranslateStatistic table with languages

RAILS_HOME = File.expand_path(File.join(File.dirname(__FILE__)+"/../.."))
ENV['RAILS_ENV'] = case ARGV.first
  when "p"; "production"
  when "d"; "development"
  when "t"; "test"
  else
    ARGV.first || ENV['RAILS_ENV'] || 'development'
end

require RAILS_HOME + '/config/boot.rb'
require RAILS_HOME + '/config/environment'

class TranslationScript
  def self.get_languages
      [
      ["af","Afrikaans"],
      ["sq","Albanian"],
      ["ar","Arabic"],
      ["be","Belarusian"],
      ["bg","Bulgarian"],
      ["ca","Catalan"],
      ["zh","Chinese"],
      ["hr","Croatian"],
      ["cs","Czech"],
      ["da","Danish"],
      ["nl","Dutch"],
      ["en","English"],
      ["et","Estonian"],
      ["tl","Filipino"],
      ["fi","Finnish"],
      ["fr","French"],
      ["gl","Galician"],
      ["de","German"],
      ["el","Greek"],
      ["ht","Haitian Creole"],
      ["iw","Hebrew"],
      ["hi","Hindi"],
      ["hu","Hungarian"],
      ["is","Icelandic"],
      ["id","Indonesian"],
      ["ga","Irish"],
      ["it","Italian"],
      ["ja","Japanese"],
      ["lv","Latvian"],
      ["lt","Lithuanian"],
      ["mk","Macedonian"],
      ["ms","Malay"],
      ["mt","Maltese"],
      ["no","Norwegian"],
      ["fa","Persian"],
      ["pl","Polish"],
      ["pt","Portuguese"],
      ["ro","Romanian"],
      ["ru","Russian"],
      ["sr","Serbian"],
      ["sk","Slovak"],
      ["sl","Slovenian"],
      ["es","Spanish"],
      ["sw","Swahili"],
      ["sv","Swedish"],
      ["th","Thai"],
      ["tr","Turkish"],
      ["uk","Ukrainian"],
      ["vi","Vietnamese"],
      ["cy","Welsh"],
      ["yi","Yiddish"],     
      ]

  end
  
end


# get data from en.yml file
langs = TranslationScript.get_languages
langs.each do |lang|
  TranslateStatistic.create(:lang => lang.first)
end